export enum BINANCE_API_ENDPOINTS {
  TICKER = `https://api.binance.com/api/v3/ticker/price?symbol=`,
  TICKER_24H = `https://api.binance.com/api/v3/ticker/24hr?symbol=`,
  TRADES = `https://api.binance.com/api/v3/trades?symbol=`,
  PAIRS = `https://api.binance.com/api/v3/exchangeInfo`,
}

export enum PAIRS {
  "BTCUSDT" = "BTCUSDT",
  "ETHUSDT" = "ETHUSDT",
  "SOLUSDT" = "SOLUSDT",
  "XRPUSDT" = "XRPUSDT",
  "DOGEUSDT" = "DOGEUSDT",
  "ADAUSDT" = "ADAUSDT",
  "BNBUSDT" = "BNBUSDT",
  "SUIUSDT" = "SUIUSDT",
  "LTCUSDT" = "LTCUSDT",
  "LINKUSDT" = "LINKUSDT",
  "UNIUSDT" = "UNIUSDT",
  "AVAXUSDT" = "AVAXUSDT",
  "PEPEUSDT" = "PEPEUSDT",
  "TRXUSDT" = "TRXUSDT",
  "BCHUSDT" = "BCHUSDT",
  "AAVEUSDT" = "AAVEUSDT",
  "LDOUSDT" = "LDOUSDT",
  "PROVEUSDT" = "PROVEUSDT",
  "BONKUSDT" = "BONKUSDT",
  "SOLUSDC" = "SOLUSDC",
  "ETHUSDC" = "ETHUSDC",
  "XRPUSDC" = "XRPUSDC",
  "BNBUSDC" = "BNBUSDC",
  "ADAUSDC" = "ADAUSDC",
  "SUIUSDC" = "SUIUSDC",
  "FDUSDUSDT" = "FDUSDUSDT",
  "USDCUSDT" = "USDCUSDT",
  "BTCUSDC" = "BTCUSDC",
  "SOLFDUSD" = "SOLFDUSD",
  "BNBFDUSD" = "BNBFDUSD",
  "ETHBTC" = "ETHBTC",
  "BTCFDUSD" = "BTCFDUSD",
  "XRPFDUSD" = "XRPFDUSD",
  "FDUSDUSDC" = "FDUSDUSDC",
  "USDTBRL" = "USDTBRL",
}
